name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.RS_GCP_SA_KEY }}
          export_default_credentials: true

      - name: Create Artifact Registry Repository
        run: |
          gcloud artifacts repositories create rs-flask-app \
            --repository-format=docker \
            --location=REGION \
            --description="Repository for rs-flask-app Docker images" || echo "Repository already exists"

      - name: Configure Docker
        run: gcloud auth configure-docker REGION-docker.pkg.dev

      - name: Build Docker image
        run: docker build -t REGION-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/rs-flask-app/rs-gcp-flask:latest .

      - name: Push Docker image
        run: docker push REGION-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/rs-flask-app/rs-gcp-flask:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy rs-gcp-flask \
            --image REGION-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/rs-flask-app/rs-gcp-flask:latest \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated

  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.RS_GCP_SA_KEY }}
          export_default_credentials: true

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve
